### ISSUE TITLE
Unable to display path/target: error: ArgumentNullException: Value cannot be null. [BUG]

### ISSUE THREAD

**Issue by pinak1999** [Neogoma/stardust-SDK#83] opened 2023-04-12 06:07 UTC
**Describe the bug**
On successful relocation the drop down shows all the list of poi available after that whenever u select any POIs it throws an error

![image](https://user-images.githubusercontent.com/117369879/231365808-04055bab-b223-4545-8f22-e39182bac149.png)

**To Reproduce**

Open relocation and navigation scene [Scene name]
Do locate yourself and click on any POIs
nothing happens after that

**Expected behavior**
show the path

**Screenshots**

Unity version
Unity: 2021.0.3
ARFoundation/ARcore: [5.0.5]

Smartphone (please complete the following information):

Device: pixel 7
Version: android 13
Browser (if the issue is about navigator or dashboard):

Browser: [e.g. Chrome/Opera...]
Sessions information
Session ID [e.g. 1]
First mapping or update

Additional context
Add any other context about the
[com.neogoma.stardustsdksample-logcat.txt](https://github.com/Neogoma/stardust-SDK/files/11207663/com.neogoma.stardustsdksample-logcat.txt)
problem here.
LOGS:

**Comment by handrianj** [comment] 2023-04-12 06:48
We're aware of the problem recently. In what language is your phone? (French? Russian?)

**Comment by pinnakkkk** [comment] 2023-04-12 06:55
It's in US English.
Is there any quick fix? (Any version i can roll back to?)
> We're aware of the problem recently. In what language is your phone? (French? Russian?)

**Comment by handrianj** [comment] 2023-04-12 10:00
You can use branch 1.14 which we pushed a few hours ago.

**Comment by pinak1999** [comment] 2023-04-12 12:28
> branch 1.14 which

im still getting the same error :(

**Comment by pinak1999** [comment] 2023-04-12 19:16
> Can you provide us with a map UUID to replicate the problem? We can't replicate the issues with the navigation on the branch 1.14

yes it works now but why does the target drift? and on relocation the targets are just far elsewhere there was an issue with xr session position thats why the cords where 600 > but even after resetting the relocation is not accurate
so here's how i do it 
click on play
create first target start or something 
moving from POIs to POIs
stop 
let it complete the upload 
then hit the generate button

after that

**Comment by handrianj** [comment] 2023-04-12 22:45
> why does the target drift? 

Target drifts are likely caused by phone drifting. Drifting and bad mapping data usually happen on low-end phones that can't keep a consistant SLAM with ARCore. Since the initial problem has been solved I will close this issue.

**Closed by handrianj** 2023-04-12 22:45 UTC
Labels: bug
